plone/plone.app.content

CHANGES.rst
plone/app/content/browser/folder.py

see also  https://github.com/collective/wildcard.foldercontents/pull/48

fix removing tags with non-ascii characters in folder_contents

---

CHANGES.rst
plone/app/content/browser/actions.py
plone/app/content/tests/test_actions.py
plone/app/content/tests/test_folder.py

This pull requests provides test to demonstrate the problem of deletion by acquisition referenced in plone/Products.CMFPlone#383 and fixes the issue in the delete confirmation view by comparing the inner and outer acquisition chains of the object to be deleted.

Address the question of deletion by acquisition

---

CHANGES.rst
plone/app/content/browser/vocabulary.py
plone/app/content/tests/test_widgets.py

Let ``@@getVocabulary`` return the vocabulary's value instead of the token for the id in the result set. The token is binary encoded and leads to encoding errors when selecting a value with non-ASCII data from vocabulary list in a select2 based widget.  Fixes: https://github.com/plone/Products.CMFPlone/issues/650

Fix encoding problems with Mockup Select2 widget

---

CHANGES.rst
plone/app/content/browser/actions.py

To reproduce:
Create a folder with a unicode character in the title, and try to delete it via the @@delete_confirmation view. A UnicodeDecodeError is thrown on line 72.
The reason is that obj.Title() gives us a bytestring, but I'm not sure if we should just use the title attribute instead (as in this PR), or if there's a reason to use Title() and decode it before returning the status message.

Bugfix: allow deletion of items with unicode characters in the title

---

CHANGES.rst
plone/app/content/browser/contents/defaultpage.py
plone/app/content/tests/test_actions.py
plone/app/content/tests/test_folder.py
plone/app/content/tests/test_selectdefaultpage.py

``folder.default_page`` is not an api and only works under certain circumstances. ``folder.getDefaultPage()`` is official api,

fix tests: correct API usage to get the currently set default page

---

CHANGES.rst
plone/app/content/browser/actions.py
plone/app/content/tests/test_actions.py

With changelog entry and tests.

fix: allow unicode in object title when using actions

---

plone/app/content/browser/i18n.py

Simply try the base language if no region specific translation catalog is available.

fix issue with i18njs and regional language variants

---

CHANGES.rst
plone/app/content/browser/vocabulary.py
plone/app/content/tests/test_widgets.py

(The autocomplete widget sends a text query rather than a JSON-encoded querystring query.)
This is needed to work for sources that implement a `search` method but not `search_catalog`,
such as the UsersSource in plone.app.vocabularies.

make @@getSource work for autocomplete widget

---

CHANGES.rst
plone/app/content/browser/contents/__init__.py
plone/app/content/browser/contents/rearrange.py

If the context does not have getOrdering, it will take the one from the parent folder. I have the issue with an archetype content type, I'm not sure how to get ordering right now, but this ensure it will not try to rearrange something else.
This PR also includes a fix to the error message generation. Tell me if you want me to split these commits.

Fix rearrange

---

CHANGES.rst
plone/app/content/browser/actions.py

Not changing the id caused the id to become the old id with "-1" appended.

fix: do not rename when only changing title

---

CHANGES.rst
plone/app/content/browser/vocabulary.py

https://github.com/plone/Products.CMFPlone/issues/1398

added translation functionality to folder content panel

---

CHANGES.rst
plone/app/content/browser/contents/__init__.py
plone/app/content/tests/test_folder.py

Fix folder contents path and breadcrumbs settings to show correct paths and render the toolbar correctly in navigation root subsites and virtual hosting environments pointing to subsites.
Folder contents should be navigatable through the whole site, even if a subsite is somewhere below IPloneSiteRoot. Being on that context, getSite() returned previously the subsite and folder_contents started to not properly display the breadcrumbs and could call @@render-toolbar, because it was called on a nonexistent context.
Finding the top-most ISite object, which is accessable within the URL path's boundaries, the structure pattern can handle this properly again.
/me not very proud of this code.
/cc @jensens

folder contents: fix breadcrumbs and toolbar for subsites and VH

---

CHANGES.rst
plone/app/content/browser/vocabulary.py
plone/app/content/tests/test_widgets.py

should fix current broken coredev tests

fix vocabulary permissions for non-registered vocabs by providing a default

---

CHANGES.rst
plone/app/content/basecontent.rst
plone/app/content/browser/contents/__init__.py
plone/app/content/browser/contents/paste.py
plone/app/content/browser/contents/properties.py
plone/app/content/browser/contents/tags.py
plone/app/content/browser/vocabulary.py
plone/app/content/tests/test_basecontent.py
plone/app/content/tests/test_contents.py
plone/app/content/tests/test_widgets.py
setup.py

- Folder contents: Acquire the top most visible portal object to operate on.
Fixes some issues in INavigationRoot or ISite based subsites and virtual hosting environments pointing to subsites.
Fixes include: show correct breadcrumb paths, paste to correct location.
Fixes: #86 
- Folder contents: When pasting, handle "Disallowed subobject type" ValueError and present a helpful error message.
Fixes: plone/mockup#657

More folder contents fixes

---

CHANGES.rst
plone/app/content/browser/vocabulary.py

Since 3.1, the ``_permissions`` variable was ``None`` instead of a backwards compatibility alias for ``PERMISSIONS`` due to a wrong deprecation.
Problem was introduced in pull request #85.

Properly deprecated _permissions in favor of PERMISSIONS. [master]

---

CHANGES.rst
plone/app/content/browser/vocabulary.py

Since 3.1, the ``_permissions`` variable was ``None`` instead of a backwards compatibility alias for ``PERMISSIONS`` due to a wrong deprecation.
Backport of pull #95

Properly deprecated _permissions in favor of PERMISSIONS. [3.1]

---

CHANGES.rst
plone/app/content/browser/__init__.py
plone/app/content/browser/configure.zcml
plone/app/content/browser/constraintypes.py
plone/app/content/browser/contents/__init__.py
plone/app/content/browser/contents/delete.py
plone/app/content/browser/file.py
plone/app/content/browser/i18n.py
plone/app/content/browser/query.py
plone/app/content/browser/vocabulary.py
plone/app/content/tests/test_contents.py

- Add ``@@allow_upload`` view, which returns a JSON string to indicate if File or Image uploads are allowed in the current container.
- Explicitly set ``application/json`` content type for JSON responses and declare an ``utf-8`` charset.

allowUpload JSON view, content-type json for all

---

CHANGES.rst
plone/app/content/utils.py

Somehow on one of our clients Website we get that error on "folder_listing",
"circular reference" happens when json_dumps gets a unparseable data type.
Other people also have this error:
https://community.plone.org/t/problem-with-listing-folder-content/2271/4
Signed-off-by: Rene Jochum <rene@jochums.at>

Fix a circular reference error in the json dumper.

---

CHANGES.rst
plone/app/content/browser/contents/templates/properties.pt
plone/app/content/browser/contents/templates/rename.pt

- Folder contents properties dialog: Fix form request variables for ``effective`` and ``expiration`` dates.
- Folder contents rename dialog: In the rename dialog, show image thumbnails in ``thumb`` scale instead of ``icon``. Plones standard ``icon`` scale is way to small to be useful for images.
Part of: https://github.com/plone/mockup/pull/696

folder contents properties fix + rename images scale

---

CHANGES.rst
plone/app/content/browser/contents/__init__.py

Fix issue with ``get_top_site_from_url``, where in some circumstances a ValueError was thrown.
If that happens, just return ``getSite``.
You will only notice, if you have subsites, access them non-VirtualHost-rooted and an error is thrown.
Then folder contents won't be able to navigate up to the root Plone site.
Fixes #103.

Fix get_top_site_from_url, Issue #103.

---

CHANGES.rst
plone/app/content/browser/contents/__init__.py

Credits go to @keul and @ekulos that found it yesterday.
If between two strings there are only whitespaces (like between ``'location'`` and ``'ModificationDate'``) python merges them to ``locationModificationDate``.

Mind the comma

---

CHANGES.rst
plone/app/content/browser/file.py
plone/app/content/tests/test_contents.py

Fixes a case, where ``@allow_upload`` reported ``True`` for content of type ``File``.

Check for containerish behavior in ``@@allow_upload``.

---

CHANGES.rst
plone/app/content/browser/vocabulary.py

I need to override some variable in `BaseVocabularyView` but they aren't easily accessible as of right now. This solves it.

Allow for easier override of BaseVocabularyView settings

---

CHANGES.rst
plone/app/content/browser/contents/__init__.py
plone/app/content/browser/contents/paste.py
plone/app/content/tests/test_contents.py

Fixes https://github.com/plone/plone.app.content/issues/123
The new tests will fail with current CMFPlone master for Plone 5.1 until https://github.com/plone/Products.CMFPlone/pull/1996 (similar regression in catalog search)

Fix issue where some folder actions failed when path above had privat levels

---

CHANGES.rst
plone/app/content/browser/contents/__init__.py
plone/app/content/browser/contents/delete.py
plone/app/content/browser/contents/rearrange.py
plone/app/content/browser/contents/rename.py
plone/app/content/browser/contents/workflow.py

This allows deleting, renaming, rearranging and changing workflow of content which expiration date has already been met or which effective date hasn't met yet.
@datakurre , @jensens & @mauritsvanrees this might be of interest for you.
AFAIK, this shouldn't have anything to do with my PR https://github.com/plone/Products.CMFPlone/pull/1952 and this bug should already been present in Plone 5.0.
I'll deliver tests later, I have to run.

Allow operation on inactive content for all folder content actions.

---

CHANGES.rst
plone/app/content/browser/contents/__init__.py

Folder Contents: Construct the list of sortable indexes from the available catalog indexes, using a blacklist and a default set - likewise as it's done with metadata columns.

folder contents: more sort options

---

CHANGES.rst
plone/app/content/browser/contents/__init__.py
plone/app/content/browser/templates/select_default_page.pt
plone/app/content/browser/vocabulary.py

(uses site control panel settings: thumb_size_tables ...)
https://github.com/plone/Products.CMFPlone/issues/1734

make thumb size in folder contents listing adjustable/supressable

---

CHANGES.rst
plone/app/content/browser/contents/copy.py
plone/app/content/browser/contents/cut.py
plone/app/content/browser/contents/delete.py
plone/app/content/browser/contents/paste.py
plone/app/content/browser/contents/properties.py
plone/app/content/browser/contents/rename.py
plone/app/content/browser/contents/tags.py
plone/app/content/browser/contents/workflow.py

Folder Contents: More compact toolbar
Instead of showing titles in the menu bar action buttons, show only icons and add a tooltip.
This makes the menu bar more compact and avoids breaking into two lines.
Also: Better icons for copy and paste.
Merge all these:
https://github.com/plone/plone.app.content/pull/138
https://github.com/plone/mockup/pull/811
https://github.com/plone/Products.CMFPlone/pull/2164

Folder Contents: More compact toolbar

---

CHANGES.rst
plone/app/content/browser/contents/delete.py

In the pop-over form when deleting something, there were some "missing" translations (some labels weren't translated when rendered in the template).
Now they get translated before being sent to the template, solving the problem.

Fixed some translations in the delete pop-over

---

CHANGES.rst
plone/app/content/browser/i18n.py

This avoids ``BadRequest`` errors, when being called without a domain url query string.

Allow ``plonejsi18n`` accept empty domains when calling.

---

CHANGES.rst
plone/app/content/browser/contents/__init__.py
plone/app/content/browser/contents/copy.py
plone/app/content/tests/test_contents.py

Fixes: https://github.com/plone/Products.CMFPlone/issues/1875
plone.app.content.browser.contents.ContentsBaseView did a catalog call with the selection list, which is a list of UUIDs. The order isn't preserved in that case. 
My fix preserves the order in which they were selected - not necessarily the original sort order of the folder the items are copied from. When doing a "select all" in the folder contents view, the selection is done in the folder's sort order. I think this gives more flexibility to power users.
Note: The reason why I fixed the selection order only for the copy view (``plone.app.content.browser.contents.copy.CopyActionView``) is because there were a lot of tests failing when I tried to apply this for ``plone.app.content.browser.contents.ContentsBaseAction``.
In some …

Folder contents: When copying items keep the order in which they were selected.

---

CHANGES.rst
plone/app/content/browser/i18n.py

plonejsi18n view currently support only the first .po file, but many tmes there is a need to add new translation or override defaults, using other .po files on same i18n domain.
this PR try to fix this.

Added support for multiple po file on same i18n domain for plonejsi18n view.

---

CHANGES.rst
plone/app/content/basecontent.rst
plone/app/content/testing.py
plone/app/content/tests/base.py
plone/app/content/tests/test_basecontent.py

The bbb module uses ZopeTestCase, which end ups creating test isolation problems.
See https://github.com/plone/Products.CMFPlone/issues/2290

Remove p.a.testing.bbb usage

---

CHANGES.rst
plone/app/content/browser/contents/rearrange.py
plone/app/content/tests/test_folder.py

I ran into a bug in plone 5.1 (latest) where the drag & drop of content items in the root plone folder doesn't work. This PR fixes it.
Cheers, Huub

fix drag & drop in folder listing on plone root

---

CHANGES.rst
plone/app/content/browser/contents/workflow.py
plone/app/content/tests/test_folder.py

Problem: changing state from the toolbar and from the folder_contents view have different results.
The first reindex the catalog, and updates effective and modified date.
The second only set effective_date field attribute to the object, but the indexes are not updated.
For example publishing a document with folder_contents generates inconsistent catalog status:
- modified date: not touched
- effective: metadata is correctly updated, but the index is the default one (1969/01/01)
With this change, we will call a reindexObject() after every state change

ReindexObject when change state

---

CHANGES.rst
plone/app/content/browser/content_status_history.py
plone/app/content/browser/templates/content_status_history.pt

Replaces skin script getObjectsFromPathList.py. The option for batching seems to be unused in the skin script so I didn't port it.
See https://github.com/plone/Products.CMFPlone/issues/1801

Added get_objects_from_path_list

---

CHANGES.rst
plone/app/content/browser/file.py
plone/app/content/browser/reviewlist.py
setup.py

Use obj.get_size() instead of getObjSize skin script.
Allows removing the script and also returns a numerical value which is more consistent with what is returned in the other cases.
See also https://github.com/plone/Products.CMFPlone/issues/1801

Use get_size instead of getObjSize

---

CHANGES.rst
plone/app/content/browser/content_status_history.py
plone/app/content/browser/templates/content_status_history.pt

No longer pass message to the method since the message parameter wasn't used
by the original script anyway.

re #1801: add redirect_to_referrer to replace skin script

---

CHANGES.rst
plone/app/content/browser/contents/copy.py
plone/app/content/browser/contents/cut.py
plone/app/content/browser/contents/delete.py
plone/app/content/browser/contents/paste.py
plone/app/content/browser/contents/properties.py
plone/app/content/browser/contents/rename.py
plone/app/content/browser/contents/tags.py
plone/app/content/browser/contents/workflow.py
plone/app/content/tests/test_contents.py

They need to be relative to the site root (resp. top site from url due to path handling in the structure pattern) and contain a {path} placeholder.
Fixes: https://github.com/plone/mockup/issues/857
**Targets Plone 5.1, p.a.content 3.5.x branch**
Merge together:
https://github.com/plone/mockup/pull/876
https://github.com/plone/plone.app.content/pull/167
https://github.com/plone/Products.CMFPlone/pull/2577

Fix URLs in folder_contents action buttons.

---

CHANGES.rst
plone/app/content/browser/actions.py
plone/app/content/browser/contents/delete.py

The presence of a request causes them to try to render a ZMI page,
which is unnecessary and now breaks due to a permission check.

Fix actions using Zope manage_ methods by not passing a request.

---

news/186.bugfix
plone/app/content/browser/templates/object_rename.pt

the form description is already present in p.a.z3cform titlelessform macro https://github.com/plone/plone.app.z3cform/blob/966b3e6a626c71c7270519540044d0831db7a819/plone/app/z3cform/templates/macros.pt#L43

form description duplicated

---

news/182.bugfix
plone/app/content/browser/selection.py
plone/app/content/tests/test_selectdefaultpage.py

Fixes #182 in 3.5.x branch (Plone 5.1)
Merge together: https://github.com/plone/Products.CMFPlone/pull/2954

Follow default_page_types setting when showing the items that can be selected as default page (Plone 5.1)

---

news/189.feature
plone/app/content/browser/contents/__init__.py

This is how it works today:
This is how it will work, if this PR is merged

folder_contents filter should not use SearchableText, but Title

---

news/191.bugfix
plone/app/content/browser/contents/workflow.py
plone/app/content/testing.py
plone/app/content/tests/profiles/non-ascii-workflow-profile/workflows.xml
plone/app/content/tests/profiles/non-ascii-workflow-profile/workflows/non-ascii-workflow/definition.xml
plone/app/content/tests/profiles/non-ascii-workflow.zcml
plone/app/content/tests/test_non_ascii_characters_in_workflow_state.py

Close https://github.com/plone/plone.app.content/issues/179
TODO:
Instead of doing this fix in `ftw.lawgiver` (https://github.com/4teamwork/ftw.lawgiver/pull/97) we instead should fix the issue at its source.
The change allows the use of non-ASCII characters in workflow state titles. In many languages apart from English, this could be a requirement.  
Since users can see the workflow state title when doing transitions it should definitely be possible to use non-ASCII as well.

Fix unicode error.

---

news/3021.bugfix
plone/app/content/browser/contents/__init__.py
plone/app/content/tests/test_contents.py

Part of https://plone.org/security/hotfix/20200121/xss-in-the-title-field-on-plone-5-0-and-higher

Integrate Plone20200121 hotfix: prevent XSS in title. [master]

---

news/3021.bugfix
plone/app/content/browser/contents/__init__.py
plone/app/content/tests/test_contents.py

Part of https://plone.org/security/hotfix/20200121/xss-in-the-title-field-on-plone-5-0-and-higher
For Plone 5.1.
Backport of PR #193

Integrate Plone20200121 hotfix: prevent XSS in title. [3.5.x]

---

news/203.bugfix
plone/app/content/browser/contents/__init__.py
plone/app/content/configure.zcml
setup.py

Related to https://github.com/plone/plone.app.contenttypes/pull/559 to avoid code duplication.
I added plone.app.contenttypes to install_requires, this was already a dependency for the tests.
This PR needs to be tested and merged after https://github.com/plone/plone.app.contenttypes/pull/559

consume the metadatafields vocabulary for translated columns

---

news/204.bugfix
plone/app/content/browser/contents/properties.py
plone/app/content/browser/contents/workflow.py

Pass messages from translate method to get them translated in JSON results used later by folder_contents view

---

news/206.bugfix
plone/app/content/browser/contents/properties.py
plone/app/content/browser/contents/templates/properties.pt

This way the popover shown in folder_contents view renders the pickadate widget with the proper language settings.

Expose pickadate pattern options in property editing template

---

news/147.bugfix
plone/app/content/browser/contents/__init__.py

Required for https://github.com/plone/mockup/pull/1005

Pass default_page_types to allow respecting that in folder_contents

---

news/3130.bugfix
plone/app/content/browser/vocabulary.py
plone/app/content/tests/test_widgets.py

```
DeprecationWarning: IFieldPermissionChecker is deprecated.
Import IFieldPermissionChecker from plone.app.z3cform.interfaces instead
```

Fixed deprecation warning for IFieldPermissionChecker.

---

news/3057.breaking
plone/app/content/browser/configure.zcml
plone/app/content/browser/folder_publish.py
plone/app/content/tests/test_folder_publish.py
setup.py

This replaces the `folder_publish.cpy` script from `Products.CMFPlone`.
I would say should should only be done on Plone 6, so I bumped the version.
I change `sources.cfg` in 5.2 to use new branch `3.x`.

Add folder_publish browser view.

---

CHANGES.rst
news/215.breaking
plone/app/content/basecontent.rst
plone/app/content/browser/actions.py
plone/app/content/browser/constraintypes.py
plone/app/content/browser/contents/__init__.py
plone/app/content/browser/contents/rename.py
plone/app/content/browser/file.py
plone/app/content/browser/folderfactories.py
plone/app/content/browser/reviewlist.py
plone/app/content/browser/tableview.py
plone/app/content/browser/templates/select_default_page.pt
plone/app/content/browser/vocabulary.py
plone/app/content/container.py
plone/app/content/namechooser.py
plone/app/content/namechooser.txt
plone/app/content/testing.py
plone/app/content/tests/test_actions.py
plone/app/content/tests/test_contents.py
plone/app/content/tests/test_folder.py
plone/app/content/tests/test_folder_publish.py
plone/app/content/tests/test_reviewlist.py
plone/app/content/tests/test_selectdefaultpage.py
plone/app/content/tests/test_widgets.py
setup.py

Note that master is already only used on Plone 6, so we can safely cleanup.
This removes Archetypes, fixes deprecation warnings, removes six, removes no longer needed compatibility imports, and fixes a few flake8 warnings. (The remaining flake8 warnings could be fixed by calling `black`.)
If the diff is too large, you can look at the individual commits, most of which are small.

Remove compatibility code for Archetypes and older Pythons and Plones

---

news/221.bugfix
plone/app/content/browser/vocabulary.py
plone/app/content/tests/test_widgets.py
setup.py

Allow to use the `@@getSource` view when we are in an add form and we do not have the "Modify portal content" permission
Refs #221

Fix permission checks for the @@getSource view (Plone 5.2)

---

news/221.bugfix
plone/app/content/browser/vocabulary.py
plone/app/content/tests/test_widgets.py
setup.py

Allow to use the `@@getSource` view when we are in an add form and we do
not have the "Modify portal content" permission
Fixes #221

Fix permission checks for the @@getSource view (Plone 6)

---

news/234.bugfix
plone/app/content/browser/constraintypes.py

Used translations have been merged into plone domain as part of https://github.com/collective/plone.app.locales/pull/331

update i18n domain to be plone

---

news/2921.bugfix
plone/app/content/browser/vocabulary.py

Fixes https://github.com/plone/Products.CMFPlone/issues/2921 for 5.2.

Fix TypeError: 'NoneType' object is not subscriptable [5.2]

---

news/3858.internal
plone/app/content/tests/test_constrains.py
plone/app/content/tests/test_permissions.py

There is still the `INameFromTitle`, _one piece at a time_ 🎶 
This goes together with https://github.com/plone/plone.app.dexterity/pull/378
Part of https://github.com/plone/Products.CMFPlone/issues/3858

Break dependency with plone.app.dexterity

---

news/3858.internal
news/3858.internal.2
plone/app/content/interfaces.py
plone/app/content/namechooser.py
plone/app/content/namechooser.txt

Part of https://github.com/plone/Products.CMFPlone/issues/3858
This needs https://github.com/plone/plone.base/pull/51 to be merged and released.
It needs all other mentioned PRs on the tracking issue to be merged first.

Move `INameFromTitle` interface to `plone.base`

---

news/3874.bugfix
plone/app/content/browser/vocabulary.py
plone/app/content/tests/test_widgets.py

see https://github.com/plone/Products.CMFPlone/issues/3874
I tried to change the `parser` here https://github.com/plone/Products.PortalTransforms/blob/master/Products/PortalTransforms/transforms/safe_html.py#L187 to `html.XHTMLParser(encoding="utf-8", resolve_entities=False, recover=True)` but this removes all entities in the string and leads to many testing failures.
Note that this only affects `@@getVocabulary` BrowserView when no attributes are passed in the request ~~and for this special `&` case. Wonder if there is a more generic solution for more cases out there?~~ Update: I think its ok to unescape all entities.

Fix escaped html entities in vocabulary items

---

news/125.bugfix
plone/app/content/browser/templates/select_default_page.pt

Usage of ``visible_ids`` was largely removed in Plone 5.0 already, and you cannot change the setting on the portal or the member. This was using the deprecated ``portal_properties`` tool. See also https://github.com/plone/plone.app.contenttypes/pull/693
I think this is fine in Plone 6.0 already.
If this part was still working, then the 'select default page' form would look like this, showing the ids in brackets.  Sorry, Dutch text:

No longer check visible_ids on the 'select default page' form.

---

news/287.bugfix
plone/app/content/browser/vocabulary.py

… instead of individual items
This saves a lot of runtime for large vocabularies like Keywords. On a site with 30,000 keywords the request time went down from 13 seconds to under a second.

getVocabulary: Call scrub_html on the end result

---

news/3654.bugfix
plone/app/content/browser/constraintypes.py

fixes [#3654](https://github.com/plone/Products.CMFPlone/issues/3654)

Fixes folder_constraintypes_form breaking with `no value` option being chosen
