- CHANGES.rst
- plone/app/content/browser/constraintypes.py
https://github.com/plone/Products.CMFPlone/issues/584
> Fixes https://github.com/plone/Products.CMFPlone/issues/584

- CHANGES.rst
- plone/app/content/browser/actions.py
- plone/app/content/tests/test_actions.py
> When clicking cancel on the delete_confirmation got to the view_url

- CHANGES.rst
- plone/app/content/browser/contents/__init__.py
- plone/app/content/browser/contents/configure.zcml
- plone/app/content/browser/contents/copy.py
- plone/app/content/browser/contents/cut.py
- plone/app/content/browser/contents/defaultpage.py
- plone/app/content/browser/contents/delete.py
- plone/app/content/browser/contents/paste.py
- plone/app/content/browser/contents/properties.py
- plone/app/content/browser/contents/rearrange.py
- plone/app/content/browser/contents/rename.py
- plone/app/content/browser/contents/tags.py
- plone/app/content/browser/contents/workflow.py
- plone/app/content/browser/file.py
- plone/app/content/tests/test_folder.py
- setup.py
includes minor refactorings to make the code structure consistent.
> Add test for folder contents rearrange feature 

- plone/app/content/browser/actions.py
It was an hack to fix some issues with pat-modal.
It is better to fix pat-modal
> Remove a different behaviour on ajax calls

- plone/app/content/browser/actions.py
- plone/app/content/tests/test_actions.py
fix https://github.com/plone/Products.CMFPlone/issues/829
> Respect view-methods in rename, copy and cut

- plone/app/content/browser/actions.py
- plone/app/content/browser/contents/delete.py
- plone/app/content/browser/contents/templates/delete.pt
- plone/app/content/browser/templates/delete_confirmation.pt
This is part of the Linkintegrity-PLIP #698
Only merge together with plone/plone.app.linkintegrity#22 and its other dependencies.
> Linkintegrity

- CHANGES.rst
- plone/app/content/browser/file.py
- plone/app/content/tests/test_widgets.py
> Fix upload of txt files in folder contents

- plone/app/content/browser/contents/__init__.py
This pull request provides a possible solution to:
**Unable to add custom columns to folder content - https://github.com/plone/Products.CMFPlone/issues/1278**
The `folder_contents` view provides a limited list of availableColumns that the user can select from. If I add a new field to my content types I can't display this extra data as a column. This change tidies up the default list of [available columns](https://github.com/plone/mockup/blob/master/mockup/patterns/structure/pattern.js#L63) and then allows the user to select any extra metadata columns that have been defined in the catalog.
> Add custom metadata columns to available columns in folder contents

- CHANGES.rst
- plone/app/content/testing.py
- plone/app/content/tests/test_widgets.py
This removes a test isolation problem and removes an unnecessary test dependency on plone.app.widgets.
> Fix test isolation problem

- CHANGES.rst
- plone/app/content/testing.py
- plone/app/content/tests/test_widgets.py
Reverts plone/plone.app.content#79
Should fix jenkins failures introduced here: http://jenkins.plone.org/job/plone-5.0-python-2.7/4346/ and here: http://jenkins.plone.org/job/plone-5.1-python-2.7/98/
> Revert "Fix test isolation problem"

- CHANGES.rst
- plone/app/content/testing.py
- plone/app/content/tests/test_widgets.py
Attempt 2 with identical commit like in https://github.com/plone/plone.app.content/pull/79
> Fix test isolation problem and remove an unnecessary test dependency on plone.app.widgets.

- CHANGES.rst
- plone/app/content/browser/file.py
fixes https://github.com/plone/Products.CMFPlone/issues/1553
> Correct how Type is looked Up

- CHANGES.rst
- plone/app/content/browser/contents/workflow.py
> fix recursive workflow actions

- CHANGES.rst
- plone/app/content/browser/reviewlist.py
> Fix issue where full review list failed with non-ascii characters in creator name

- CHANGES.rst
- plone/app/content/basecontent.rst
- plone/app/content/tests/test_widgets.py
Part of PLIP 1343: https://github.com/plone/Products.CMFPlone/issues/1343
> Merge collective indexing

- CHANGES.rst
- plone/app/content/tests/test_namechooser_unit.py
see https://github.com/plone/Products.CMFPlone/issues/1882
> removed unittest2

- CHANGES.rst
- plone/app/content/browser/contents/__init__.py
Followup of https://github.com/plone/Products.CMFPlone/issues/1734
> Cleanup of PLIP #1734

- CHANGES.rst
- plone/app/content/utils.py
- setup.py
fixes https://github.com/plone/plone.app.content/issues/134
> Use simplejson because it's ahead of stdlib and supports more types

- CHANGES.rst
- plone/app/content/browser/contents/__init__.py
- plone/app/content/browser/contents/properties.py
- plone/app/content/browser/contents/templates/properties.pt
- plone/app/content/tests/test_contents.py
- Folder contents properties: Add settings to change the content language.
- Folder contents properties: Add a recursion feature to apply all changes recursively.
Merge all:
https://github.com/plone/plone.app.content/pull/133
https://github.com/plone/plone.app.dexterity/pull/251
https://github.com/plone/plone.app.vocabularies/pull/50
> @@fc-properties: Apply recursively + set language

- CHANGES.rst
- plone/app/content/browser/vocabulary.py
Fix for plone/Products.CMFPlone#2174
> Fix fulltext filter with alternative indexes 

- CHANGES.rst
- plone/app/content/browser/contents/properties.py
There already is a `dx_action` method, having one for AT would be useful as well.
> move AT specific code in PropertiesActionView in its own method

- CHANGES.rst
- plone/app/content/browser/contents/__init__.py
Fixes: https://github.com/plone/Products.CMFPlone/issues/2199
> Fix sorting by last modified

- CHANGES.rst
- plone/app/content/browser/reviewlist.py
...which is going to be removed.
https://github.com/plone/Products.CMFPlone/issues/1801
> Replaced usages of my_worklist.py skin script

- plone/app/content/browser/content_status_history.py
- plone/app/content/browser/templates/content_status_history.pt
See
https://github.com/plone/plone.app.content/pull/163/files
https://github.com/plone/Products.CMFPlone/issues/1801
> Replaced another usage of getObjSize

- CHANGES.rst
- plone/app/content/browser/content_status_history.py
- plone/app/content/browser/reviewlist.py
- plone/app/content/browser/templates/content_status_history.pt
See https://github.com/plone/Products.CMFPlone/issues/1801
> Use isExpired util method instead of isExpired.py skin script.

- news/170.bugfix
- plone/app/content/namechooser.py
- plone/app/content/namechooser.txt
Still use check_id method or skin script first.
See #170.
Test in combination.
> Use check_id function from CMFPlone.utils. [3.5.x/5.1]

- news/182.bugfix
- plone/app/content/browser/selection.py
- plone/app/content/tests/test_selectdefaultpage.py
Fixes #182 
Merge together: https://github.com/plone/Products.CMFPlone/pull/2955
> Follow default_page_types setting when showing the items that can be selected as default page

- news/197.bugfix
- news/198.bugfix
- plone/app/content/browser/vocabulary.py
- plone/app/content/tests/test_contents.py
- plone/app/content/tests/test_widgets.py
- setup.py
Fixes #197
Also updates the package to use unittest.mock on Python 3
Fixes #198
> Do not break with unknown MIME types

- news/202.bugfix
- plone/app/content/browser/constraintypes.py
This fixes https://github.com/plone/Products.CMFPlone/issues/3127
> Fix i18n of Save and Cancel buttons and the constrain types select values

- news/225.bugfix
- plone/app/content/browser/contents/__init__.py
(cherry picked from commit 068c757ff444bf08b243520d2912762c521d4b27)
> call fileUpload view explict with @@ to avoid rest clashes

- news/232.bugfix
- setup.py
> Remove cyclic dependency with Products.CMFPlone.

- news/236.bugfix
- plone/app/content/tests/test_folder.py
- plone/app/content/tests/test_widgets.py
The following PR should be merged together:
https://github.com/plone/plone.app.content/pull/236
https://github.com/plone/plone.app.contentlisting/pull/39
https://github.com/plone/plone.app.contenttypes/pull/616
https://github.com/plone/plone.app.upgrade/pull/264
https://github.com/plone/plone.restapi/pull/1251
https://github.com/plone/Products.CMFPlone/pull/3343
> Portal in the catalog

- news/240.breaking
- plone/app/content/browser/content_status_history.py
- plone/app/content/browser/templates/content_status_history.pt
> Use the human_readable_size method from the @@plone view

- news/128.bugfix
- news/246.bugfix
- plone/app/content/utils.py
Needed for the work-in-progress image_scales catalog PR https://github.com/plone/Products.CMFPlone/pull/3521.
Fixes https://github.com/plone/plone.app.content/issues/246, which is the main problem.
Also fixes the similar https://github.com/plone/plone.app.content/issues/128.
> Various fixes for custom json handler

- news/244.bugfix
- plone/app/content/browser/vocabulary.py
> Vocabulary: Do not modify the original value

- news/2921.bugfix
- plone/app/content/browser/vocabulary.py
Fixes https://github.com/plone/Products.CMFPlone/issues/2921 for 6.0
> Fix TypeError: 'NoneType' object is not subscriptable [6.0]

- news/256.bugfix
- plone/app/content/browser/selection.py
> Fix cancel button on @@select_default_view

- news/268.bugfix
- plone/app/content/browser/folderfactories.py
Fixes https://github.com/plone/plone.app.content/issues/268
> Fix for issue 268 fixed inappropriate sort() in folderfactories

- news/266.bugfix
- plone/app/content/browser/actions.py
- plone/app/content/browser/contents/cut.py
- plone/app/content/browser/contents/delete.py
- plone/app/content/tests/test_folder.py
This refs #266 & https://github.com/plone/Products.CMFPlone/issues/3846
> Fix cut / delete for content with lock created by current user

- news/259.feature
- plone/app/content/browser/contents/properties.py
- setup.py
This needs https://github.com/plone/plone.app.z3cform/pull/155
> Fix import of deprecated `plone.app.widgets` utility

- news/281.bugfix
- plone/app/content/browser/selection.py
- plone/app/content/tests/test_actions.py
see https://github.com/plone/Products.CMFPlone/issues/3515
Transitive fix for https://github.com/plone/Products.CMFPlone/pull/3960 too
> Remove usage of skins script

- news/285.bugfix
- plone/app/content/browser/templates/content_status_history.pt
Before -> After
and replaced the old `toggleSelect()` with `pat-checklist`
> Fix BS styling in `content_status_history`

- news/268.bugfix
- plone/app/content/browser/folderfactories.py
backport of https://github.com/plone/plone.app.content/pull/269
> Fix for issue 268 fixed inappropriate sort() in folderfactories [ajung]

- news/303.bugfix.rst
- plone/app/content/browser/vocabulary.py
> @@getSource supports object widgets
